"""empty message

Revision ID: e3180169f878
Revises: 4caa1507cdd1
Create Date: 2026-02-07 12:39:34.079235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3180169f878'
down_revision = '4caa1507cdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_questions', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_saved_question', ['user_id', 'question_id'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('tag_name',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('saved_questions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_saved_question', type_='unique')

    # ### end Alembic commands ###
